# Generated by Django 4.1.3 on 2022-11-19 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=32)),
                ('grade', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('lesson', models.CharField(max_length=32)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('userId', models.IntegerField()),
                ('phone', models.CharField(max_length=32)),
                ('id_card', models.CharField(max_length=32)),
                ('identity', models.CharField(max_length=32)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagerSystem.classinfo')),
            ],
        ),
    ]
