# Generated by Django 4.1.3 on 2022-11-28 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("StudentManagerSystem", "0003_alter_userinfo_class_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="classinfo",
            name="info",
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ClassJoinInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="StudentManagerSystem.classinfo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="StudentManagerSystem.userinfo",
                    ),
                ),
            ],
        ),
    ]
