# Generated by Django 4.1.3 on 2022-11-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StudentManagerSystem", "0004_classinfo_info_classjoininfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="classinfo",
            name="if_show",
            field=models.BooleanField(default=True),
        ),
    ]
