# Generated by Django 4.1.3 on 2022-11-30 14:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("StudentManagerSystem", "0005_classinfo_if_show"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="class_info",
        ),
        migrations.AddField(
            model_name="classinfo",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="StudentManagerSystem.userinfo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mark",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
